import { RuleTester } from 'eslint';
import { generateCases } from '../generate-cases';
import InvalidTestCase = RuleTester.InvalidTestCase;
import ValidTestCase = RuleTester.ValidTestCase;

export type RuleOptionsForDocumentation = {
    code: string;
    description?: string;
}

export function rulePageDoc(
    ruleName: string,
    ruleDescription: string,
    options: RuleOptionsForDocumentation,
    invalidExamples: InvalidTestCase[],
    validExamples: ValidTestCase[],
) {
    return `<!--

  DO NOT EDIT.

  This markdown file was autogenerated using npm run docs from following files: 
  - src/rules/${ruleName}/tests/valid.ts
  - src/rules/${ruleName}/tests/invalid.ts

  In order to update this file, it is therefore those files which need to be updated, as well as potentially the generator script:
  - src/docs/generate-doc-page.ts
  or one of the templates it uses:
    - src/docs/templates/rule-page-doc.ts
    - src/docs/templates/invalid-case-doc.ts
    - src/docs/templates/valid-case-doc.ts
-->

# \`html-class-attribute/${ruleName}\`

${ruleDescription}

<br>

## Rule options

\`\`\`ts
${options.code}
\`\`\`

${options?.description ?? ''}


${generateCases(ruleName, invalidExamples, validExamples)}
`;
}
