name: Build & Release

on:
  workflow_run:
    workflows: [ "Test" ]
    types:
      - completed

permissions:
  contents: write
  actions: write

jobs:
  release-and-publish:
    # Only run job on test success and on main branch
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch the last 2 commits instead of just 1 to amend commit with doc. (Fetching just 1 commit would overwrite the whole history)
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Build doc
        run: npm run docs

      - name: Get last commit message and author
        id: last-commit
        run: |
          echo "message=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
          echo "author=$(git log -1 --pretty=\"%an <%ae>\")" >> $GITHUB_OUTPUT

      - name: Amend last commit with built files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_author: ${{ steps.last-commit.outputs.author }}
          commit_message: '${{ steps.last-commit.outputs.message }}'
          commit_options: '--amend --no-edit'
          push_options: '--force'
          skip_fetch: true

      # exec semantic-release after pushing changes
      - name: Release
        run: npx semantic-release
